name: think fwd
favicon: null
layout_spectrum: 0.3713099497836083
typography_spectrum: 0.6252334991004318
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.06240000110119581
  lightness: 0.44862060947343707
  saturation: 0.7704267343506217
  rhythmicContrast: 0.05198284797370434
purpose: []
